language: python

cache: pip

python:
  - "3.7"
  - "3.8"

install:
  - pip install -r requirements.txt

before_script:
  - pip install -r requirements_dev.txt
  - yarn

script:
  - pytest -x tests
  - isort --profile=black -c .
  - black --check .
